In [10]:
import os
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch

warnings.filterwarnings("ignore")

In [14]:
import os

RAW_DATA = "data/raw" # Updated as per your clarification
DATASET_NAME = "datasheet.xlsx" # Updated as per your clarification

DATASET_PATH = os.path.join(RAW_DATA, DATASET_NAME)

print(DATASET_PATH)

data/raw/datasheet.xlsx

In [15]:
import pandas as pd
import os

os.makedirs(RAW_DATA, exist_ok=True)

df = pd.read_excel(DATASET_PATH)

In [16]:
df.head()

,Student ID,School,Name,Gender,Class level,Parental educational level,Week1_attendance,Week2_attendance,Week3_attendance,Week4_attendance,...,Family dropout history,Child labor involvement,Travel time to school,Mode of transport,Teacher relationship quality,Peer relationship quality,Extra-curricular activities,Section,Household income level (standardized),Travel time to school (minutes)
0,1,Shining Star Preparatory,Theophilus Yaw Akyen,Female,4A,SHS,1.0,1.00,0.40,1.0,...,No,No,21 minutes,Walking,Poor,Very Good,Football,Kofi Annan,High,21.0
1,2,Shining Star Preparatory,Theophilus Yaw Akyen,Male,4B,SHS,1.0,1.00,0.25,1.0,...,No,Yes,2 Minutes,Walking,Good,Average,Drawing,Kofi Annan,High,2.0
2,3,Shining Star Preparatory,Theophilus Yaw Akyen,Male,7B3,Tertiary,0.5,0.75,1.00,1.0,...,No,No,4 minutes,Walking,Good,Good,Watch cartoons,K.A. Busia,NaN,4.0
3,4,Weweso MA,Asiama Isaac Ebenezer,Male,5,JHS,0.6,1.00,1.00,1.0,...,No,No,30 minutes,Bus,Average,Good,Drawing,Kofi Annan,High,30.0
4,5,Weweso MA,Theophilus Yaw Akyen,Male,6B,Tertiary,0.0,1.00,1.00,1.0,...,Yes,No,3 minutes,Public transport,Good,Good,Dancing,Kwegyir Aggrey,Average,3.0

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 4000
Columns: 34

In [18]:
list(df.columns)

['Student ID',
 'School',
 'Name',
 'Gender',
 'Class level',
 'Parental educational level',
 'Week1_attendance',
 'Week2_attendance',
 'Week3_attendance',
 'Week4_attendance',
 'Week5_attendance',
 'Week6_attendance',
 'Week7_attendance',
 'Week8_attendance',
 'Week9_attendance',
 'Week10_attendance',
 'Week11_attendance',
 'Week12_attendance',
 'Week13_attendance',
 'Week14_attendance',
 'Semester 1 average',
 'Semester 2 average',
 'Semester difference',
 'Household income level',
 'Family dropout history',
 'Child labor involvement',
 'Travel time to school',
 'Mode of transport',
 'Teacher relationship quality',
 'Peer relationship quality',
 'Extra-curricular activities',
 'Section',
 'Household income level (standardized)',
 'Travel time to school (minutes)']

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 34 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   Student ID                             4000 non-null   int64
 1   School                                 4000 non-null   object
 2   Name                                   4000 non-null   object
 3   Gender                                 4000 non-null   object
 4   Class level                            3983 non-null   object
 5   Parental educational level             3792 non-null   object
 6   Week1_attendance                       4000 non-null   float64
 7   Week2_attendance                       4000 non-null   float64
 8   Week3_attendance                       4000 non-null   float64
 9   Week4_attendance                       4000 non-null   float64
 10  Week5_attendance                       4000 non-null   float64
 11  Week6_attendance                       4000 non-null   float64
 12  Week7_attendance                       4000 non-null   float64
 13  Week8_attendance                       4000 non-null   float64
 14  Week9_attendance                       4000 non-null   float64
 15  Week10_attendance                      4000 non-null   float64
 16  Week11_attendance                      4000 non-null   float64
 17  Week12_attendance                      4000 non-null   float64
 18  Week13_attendance                      4000 non-null   float64
 19  Week14_attendance                      4000 non-null   float64
 20  Semester 1 average                     4000 non-null   float64
 21  Semester 2 average                     4000 non-null   float64
 22  Semester difference                    4000 non-null   float64
 23  Household income level                 4000 non-null   object
 24  Family dropout history                 4000 non-null   object
 25  Child labor involvement                4000 non-null   object
 26  Travel time to school                  4000 non-null   object
 27  Mode of transport                      4000 non-null   object
 28  Teacher relationship quality           4000 non-null   object
 29  Peer relationship quality              4000 non-null   object
 30  Extra-curricular activities            3933 non-null   object
 31  Section                                4000 non-null   object
 32  Household income level (standardized)  3738 non-null   object
 33  Travel time to school (minutes)        3999 non-null   float64
dtypes: float64(18), int64(1), object(15)
memory usage: 1.0+ MB

In [20]:
df.describe()

,Student ID,Week1_attendance,Week2_attendance,Week3_attendance,Week4_attendance,Week5_attendance,Week6_attendance,Week7_attendance,Week8_attendance,Week9_attendance,Week10_attendance,Week11_attendance,Week12_attendance,Week13_attendance,Week14_attendance,Semester 1 average,Semester 2 average,Semester difference,Travel time to school (minutes)
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,3999.000000
mean,2000.500000,0.798737,0.881612,0.852000,0.871025,0.893600,0.923650,0.897388,0.931838,0.897875,0.956063,0.899663,0.921750,0.730575,0.854025,53.843387,39.133770,-14.709618,31.740435
std,1154.844867,0.325942,0.270087,0.267447,0.313199,0.257644,0.236616,0.283521,0.201382,0.256431,0.152753,0.236028,0.188151,0.376199,0.296932,9.722749,35.954799,37.121170,31.790910
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-96.550000,1.000000
25%,1000.750000,0.600000,1.000000,0.800000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.250000,0.750000,51.490000,4.830000,-47.852500,10.000000
50%,2000.500000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,52.340000,17.910000,-25.575000,30.000000
75%,3000.250000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,54.210000,73.912500,20.142500,45.000000
max,4000.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,100.000000,100.000000,75.880000,300.000000

In [21]:
df.isnull().sum()

Student ID                                 0
School                                     0
Name                                       0
Gender                                     0
Class level                               17
Parental educational level               208
Week1_attendance                           0
Week2_attendance                           0
Week3_attendance                           0
Week4_attendance                           0
Week5_attendance                           0
Week6_attendance                           0
Week7_attendance                           0
Week8_attendance                           0
Week9_attendance                           0
Week10_attendance                          0
Week11_attendance                          0
Week12_attendance                          0
Week13_attendance                          0
Week14_attendance                          0
Semester 1 average                         0
Semester 2 average                         0
Semester difference                        0
Household income level                     0
Family dropout history                     0
Child labor involvement                    0
Travel time to school                      0
Mode of transport                          0
Teacher relationship quality               0
Peer relationship quality                  0
Extra-curricular activities               67
Section                                    0
Household income level (standardized)    262
Travel time to school (minutes)            1
dtype: int64

In [22]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [23]:
df.nunique()

Student ID                               4000
School                                      3
Name                                      421
Gender                                      2
Class level                                21
Parental educational level                  5
Week1_attendance                            9
Week2_attendance                            9
Week3_attendance                            9
Week4_attendance                            9
Week5_attendance                            9
Week6_attendance                            9
Week7_attendance                            9
Week8_attendance                            9
Week9_attendance                            9
Week10_attendance                           9
Week11_attendance                           9
Week12_attendance                           9
Week13_attendance                           9
Week14_attendance                           9
Semester 1 average                       1671
Semester 2 average                       2346
Semester difference                      3007
Household income level                     11
Family dropout history                      3
Child labor involvement                     3
Travel time to school                      85
Mode of transport                           4
Teacher relationship quality                4
Peer relationship quality                   4
Extra-curricular activities                23
Section                                     5
Household income level (standardized)       3
Travel time to school (minutes)            42
dtype: int64

In [24]:
report = {
    "Rows": df.shape[0],
    "Columns": df.shape[1],
    "Missing Values": df.isnull().sum().sum(),
    "Duplicate Rows": df.duplicated().sum()
}

report

{'Rows': 4000,
 'Columns': 34,
 'Missing Values': np.int64(555),
 'Duplicate Rows': np.int64(0)}

In [27]:
PROCESSED_DATA = "data/processed"
os.makedirs(PROCESSED_DATA, exist_ok=True)

processed_file = os.path.join(
    PROCESSED_DATA,
    "loaded_dataset.xlsx"
)

df.to_excel(processed_file, index=False)

print("Dataset copied successfully.")

Dataset copied successfully.